### ISSUE TITLE
Error: coord_fixed doesn't support free scales

### ISSUE THREAD

**Issue by cpanse** [coreforlife/c4lProteomics#4]
https://github.com/coreforlife/c4lProteomics/blob/d18241d95506b0dc2973550764e0facc953c93b1/ProteomeQR/data/TMT_EMBL/EMBL/demo_V1.Rmd#L1

label: unnamed-chunk-25 (with options) 
List of 1
 $ fig.height: num 7

Joining, by = "gene_name"
Joining, by = "gene_name"
Quitting from lines 771-819 (demo_V1.Rmd) 
Error: coord_fixed doesn't support free scales
In addition: Warning messages:
1: Column `file` joining character vector and factor, coercing into character vector 
2: Column `col.name` joining character vector and factor, coercing into character vector 
3: In rm(sdplot.object, vsn.fit) : object 'sdplot.object' not found
4: Column `ID` joining character vector and factor, coercing into character vector 
5: Column `ID` joining character vector and factor, coercing into character vector 
6: Column `ID` joining character vector and factor, coercing into character vector 
7: Column `ID` joining character vector and factor, coercing into character vector 
8: Removed 12 rows containing missing values (geom_point). 
9: Removed 12 rows containing missing values (geom_point). 

R>

**Comment by fstein** [comment]
Just remove the 'scale = "free"' from the facet_wrap comment and problem is solved...

**Comment by cpanse** [comment]
done
