### ISSUE TITLE
Modify XIC script makefile

### ISSUE THREAD

**Issue by rolivella** [coreforlife/c4lProteomics#9]
Dear @cpanse could you change a little bit the Makefile to adapt it to the QCloud pipeline folder structre? Just this: 

* The fgcz-xic.exe will be at **/bin/fgcz-xic.exe**
* The DLL libraries at **/lib/*.dll**

The other parameters can be set up at the runme.sh script so we could leave it as it is now. 

Thanks!

**Comment by cpanse** [comment]
@rolivella 

0. `/bin` is withheld for the system.  I would go for `/usr/local/bin`

DLLs should be in the same directory as the exe file unless you register the assemblies, e.g.,

1. https://www.mono-project.com/docs/advanced/assemblies-and-the-gac/

```
sudo gacutil -i ThermoFisher.CommonCore.Data.dll
sudo gacutil -i ThermoFisher.CommonCore.BackgroundSubtraction.dll
sudo gacutil -i ThermoFisher.CommonCore.MassPrecisionEstimator.dll
sudo gacutil -i ThermoFisher.CommonCore.RawFileReader.dll
```

you can enable Mono(tm) Binary Kernel Support for Linux.
2. https://www.kernel.org/doc/html/v4.15/admin-guide/mono.html

**Comment by rolivella** [comment]
@cpanse I meant /bin inside the QCloud folder structure and not inside the Linux system folder. Anyway, I'll put them in the same directory as you said. Thanks!

**Comment by rolivella** [comment]
@cpanse, by the way,
